#!/bin/bash

script_abs=$(readlink -f "$0")
script_dir=$(dirname $script_abs)
default_config=$script_dir"/tssh.ini"

NotInstall="\e[31mError.\e[0m\r\n    Please check expect was installed on your system."
command -v expect > /dev/null 2>&1 || { echo >&2 -e "$NotInstall"; exit 1; }

function usage()
{
    echo -e "
tssh [-f config][-n name][-h]

-f config:
    specify the configuration file

-n name:
    specify connect name in config file

-h:
    show help

default config file is $default_config
"
}

ConfigFile=""
Name=""

while getopts "f:n:h" OPTION; do
    case $OPTION in 
        h)
            usage
            exit -1
            ;;
        n)
            Name="$OPTARG"
            ;;
        f)
            ConfigFile="$OPTARG"
            ;;
        ?)
            usage
            exit -1
            ;;
    esac
done

# config file default to ~/.ssh.ini
if [ -z "$ConfigFile" ]; then
    ConfigFile=$default_config
fi

# check config file is exists or not
if [ ! -f "$ConfigFile" ]; then
    echo -e "\e[31mConfig File $ConfigFile Not Exists\e[0m"
    exit 1
fi

# Find profile like [xxx]
profile=`awk '$0 ~ /\[[^\]]*\]/ {print $0}' $ConfigFile | awk -F '[][]' '{print $2}'`

if [ ! -n "$profile" ];then
    echo -e "\e[31mNo Config. Please Edit config file before use.\e[0m"
    exit 1
fi

# specify name by cgi or input 
if [ ! -n "$Name" ]; then
    echo "---> Select Name to connect"
    for name in $profile
    do
        echo "         $name"
    done
    echo -n "---> Name: "
    read Name
fi

# check name is in profile or not
Flag=0
for p in $profile
do
    if [ $Name = $p ]; then
        Flag=1
    fi
done

if [ $Flag -eq 0 ]; then
    echo -e "\e[31m$Name Not in config file $ConfigFile\e[0m"
    exit 1
fi


# find host, port, user, passwd
host=`awk -F# '{print $1}' $ConfigFile | awk -F= '/\['"$Name"'\]/{a=1}a==1&&$1~/host/{print $2;exit}' | awk '{gsub(/^\s+|\s+$/, "");print}'`
port=`awk -F# '{print $1}' $ConfigFile | awk -F= '/\['"$Name"'\]/{a=1}a==1&&$1~/port/{print $2;exit}' | awk '{gsub(/^\s+|\s+$/, "");print}'`
user=`awk -F# '{print $1}' $ConfigFile | awk -F= '/\['"$Name"'\]/{a=1}a==1&&$1~/user/{print $2;exit}' | awk '{gsub(/^\s+|\s+$/, "");print}'`
passwd=`awk -F# '{print $1}' $ConfigFile | awk -F= '/\['"$Name"'\]/{a=1}a==1&&$1~/passwd/{print $2;exit}' | awk '{gsub(/^\s+|\s+$/, "");print}'`


# host could not be null
if [ -z "$host" ]; then
    echo -e "\e[31mHost Not Found for $Name\e[0m"
    exit 1
fi

# port default to 22
if [ -z "$port" ]; then
    echo -e "\e[32mUse default port: 22\e[m"
    port="22"
fi

if [ -z "$user" ]; then
    echo -e "\e[32mUser Not Found for $Name. Use default\e[0m"
    user=""
else 
    user=$user"@"
fi

ErrorPasswd="Error Password. Please Check in config file"

if [ -z "$passwd" ]; then
    ssh $user$host -p $port
else
    expect -c "
        spawn ssh $user$host -p $port
        expect {
            \"*yes/no*\" { send \"yes\r\"; exp_continue }
            \"*password:\" { send \"$passwd\r\" }
        }
        expect {
            \"*Permission denied,*\" { send_user \"\\n\033\[01;31m$ErrorPasswd\033\[0m\\n\"; exit; }
            default { interact }
        }
        interact
    "
fi 


